# Generated by Django 4.1.7 on 2023-02-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address_id', models.CharField(max_length=200)),
                ('active', models.IntegerField()),
                ('create_date', models.DateField()),
                ('last_update', models.DateField()),
            ],
        ),
    ]
